'use client';
import {Canvas,useFrame,useThree} from '@react-three/fiber';
import {useEffect,useRef} from 'react';
import type {Group} from 'three';
import type {ReplayEvent} from '@/lib/types';
function Scene({event,playing,speed,overhead,colors}:{event:ReplayEvent;playing:boolean;speed:number;overhead:boolean;colors:[string,string]}){
 const ball=useRef<Group>(null),elapsed=useRef(0),momentElapsed=useRef(2);const {camera}=useThree();
 useEffect(()=>{elapsed.current=0;momentElapsed.current=0},[event.id]);
 useEffect(()=>{camera.position.set(0,overhead?90:45,overhead?.01:58);camera.lookAt(0,0,0);camera.updateProjectionMatrix()},[camera,overhead]);
 useFrame((_,dt)=>{if(!ball.current)return;if(playing)elapsed.current+=Math.min(dt,.05)*speed;momentElapsed.current+=dt;const big=event.scoring||['Intercepted Pass','Fumble','Sack'].includes(event.result);if(big&&momentElapsed.current<.45){camera.position.x=Math.sin(momentElapsed.current*70)*.6*(1-momentElapsed.current/.45)}else camera.position.x=0;const duration=event.call==='Kick'?Math.max(1.5,Math.min(3,(event.hangTime??3)*.5)):1.5;const progress=playing?Math.min(1,elapsed.current/duration):1;const start=50-(event.yardLine??50),end=Math.max(-50,Math.min(50,start+(event.yardsGained??0)));const height=event.call==='Pass'?9:event.call==='Kick'?Math.min(20,5+(event.hangTime??3)*2):.4;ball.current.position.set(start+(end-start)*progress,1+Math.sin(Math.PI*progress)*height,0);ball.current.rotation.z=progress*Math.PI*4});
 return <><color attach="background" args={['#0d1712']}/><ambientLight intensity={1.8}/><directionalLight position={[20,70,30]} intensity={2.5}/><mesh rotation={[-Math.PI/2,0,0]}><planeGeometry args={[120,53.3]}/><meshStandardMaterial color="#174c32"/></mesh>{[-55,55].map((x,i)=><mesh key={x} position={[x,.05,0]}><boxGeometry args={[10,.1,53.3]}/><meshStandardMaterial color={colors[i]}/></mesh>)}{Array.from({length:21},(_,i)=><mesh key={i} position={[-50+i*5,.15,0]}><boxGeometry args={[.13,.1,53]}/><meshBasicMaterial color="#c9dcc7" transparent opacity={i%2? .25:.6}/></mesh>)}{[-8.5,8.5].map(z=>Array.from({length:99},(_,i)=><mesh key={`${z}-${i}`} position={[-49+i,.2,z]}><boxGeometry args={[.15,.1,1]}/><meshBasicMaterial color="#c9dcc7"/></mesh>))}<mesh position={[50-(event.yardLine??50),.25,0]}><boxGeometry args={[.25,.12,53]}/><meshBasicMaterial color="#3cbdff"/></mesh><mesh position={[Math.min(50,50-(event.yardLine??50)+(event.yardsToGo??0)),.25,0]}><boxGeometry args={[.25,.12,53]}/><meshBasicMaterial color="#f5d547"/></mesh><group ref={ball}><mesh scale={[1.2,.65,.65]}><sphereGeometry args={[1,20,12]}/><meshStandardMaterial color="#a65a32" roughness={.65}/></mesh><mesh position={[0,.65,0]}><boxGeometry args={[1,.08,.12]}/><meshBasicMaterial color="#f6ecd7"/></mesh></group></>
}
export default function Field3D(props:{event:ReplayEvent;playing:boolean;speed:number;overhead:boolean;colors:[string,string]}){return <Canvas dpr={[1,1.5]} camera={{position:[0,45,58],fov:38}}><Scene {...props}/></Canvas>}
