import games from "@/public/data/games.json";
import drives from "@/public/data/drives.json";
import scoring from "@/public/data/scoring_plays.json";
import replayEvents from "@/public/data/play_situations.json";
import teams from "@/public/data/teams_enriched.json";
import SiteNav from "@/app/components/SiteNav";
import DriveReplayLoader from "./DriveReplayLoader";
export function generateStaticParams(){return games.map(g=>({id:g.id}))}
export default async function GameFlow({params}:{params:Promise<{id:string}>}){const {id}=await params;const game=games.find(g=>g.id===id);if(!game)return <main className="data-page"><SiteNav/><div className="data-content"><h1>GAME<br/><span>NOT FOUND.</span></h1><a href="/bracket">Browse games</a></div></main>;const gd=drives.filter(d=>d.gameId===id).sort((a,b)=>Number(a.driveId)-Number(b.driveId));const moments=scoring.filter(x=>x.gameId===id).sort((a,b)=>(a.quarter??0)-(b.quarter??0)||(b.clock??0)-(a.clock??0));const max=Math.max(1,...gd.map(d=>d.events));const excerpt=replayEvents.filter(e=>e.gameId===id);const offense=game.offense.toUpperCase(),defense=game.defense.toUpperCase();const offColor=teams.find(t=>t.abbrev===offense)?.color||"#315f45",defColor=teams.find(t=>t.abbrev===defense)?.color||"#41516a";return <main className="data-page"><SiteNav/><div className="data-content"><div className="eyebrow">GAME FLOW · {game.type.toUpperCase()} · {game.date}</div><h1>{game.offense}<br/><span>{game.offenseScore} — {game.defenseScore}</span></h1><p className="dek">{game.offense} offense vs {game.defense} defense · {game.events} event rows · {game.countedPlays} source-counted events</p><DriveReplayLoader events={excerpt} offense={game.offense} defense={game.defense} offColor={offColor} defColor={defColor}/><h2>DRIVE CHART · {gd.length} DRIVE RECORDS</h2><div className="drive-list">{gd.map((d,i)=><div className="drive-row" key={`${d.driveId}-${i}`}><span>{d.team} · #{d.driveId}</span><div className="drive-track"><i style={{width:`${Math.max(5,100*d.events/max)}%`}}/></div><b>{d.events} events</b><small>{d.result}</small></div>)}</div><h2>SCORING EVENTS · {moments.length}</h2><div className="result-list">{moments.map((m,i)=><div key={`${m.team}-${i}`}><span>Q{m.quarter??"—"} · {m.clock==null?"clock unavailable":`${Math.floor(m.clock/60)}:${String(m.clock%60).padStart(2,"0")}`}</span><b>{m.team} · {m.event}{m.player?` · ${m.player}`:""}</b><small>{m.offenseScore} — {m.defenseScore}</small></div>)}</div><p className="data-source">Drive bars show event counts, not field progress. The replay displays a sample of legible scrimmage events. The scoring list shows events marked by IS_SCORING_PLAY. Clock direction has not been independently reconciled.</p></div></main>}
