'use client';
import {useState} from 'react';
import games from '@/public/data/games.json';
import teams from '@/public/data/teams_enriched.json';
type Game=typeof games[number];
type Node={game?:Game;bye?:string;depth:number;y:number;children:Node[]};
const rounds=['Wild Card Playoff','Divisional Playoff','Conf. Championship','Super Bowl'];
const postseason=games.filter(g=>g.type!=='Regular Season');
const winner=(g:Game)=>(g.offenseScore??0)>(g.defenseScore??0)?g.offense.toUpperCase():g.defense.toUpperCase();
function makeTree(){let row=0;function branch(g:Game,depth:number):Node{if(depth===0)return {game:g,depth,y:row++*130+65,children:[]};const children=[g.offense,g.defense].map(team=>{const prev=postseason.find(p=>p.type===rounds[depth-1]&&winner(p)===team.toUpperCase());return prev?branch(prev,depth-1):{bye:team.toUpperCase(),depth:depth-1,y:row++*130+65,children:[]}});return {game:g,depth,y:children.reduce((s,n)=>s+n.y,0)/children.length,children}}const final=postseason.find(g=>g.type==='Super Bowl')!;const root=branch(final,3);const nodes:Node[]=[];function walk(n:Node){nodes.push(n);n.children.forEach(walk)}walk(root);return {root,nodes,height:row*130}}
const tree=makeTree();
const branding=(team:string)=>teams.find(t=>t.abbrev===team.toUpperCase());
export default function PlayoffTree(){const [selected,setSelected]=useState(winner(tree.root.game!));return <><p className="chart-note">Select a team to light its postseason path. Open a matchup to replay the game.</p><label className="bracket-select">Follow a team <select value={selected} onChange={e=>setSelected(e.target.value)}>{[...new Set(postseason.flatMap(g=>[g.offense.toUpperCase(),g.defense.toUpperCase()]))].sort().map(t=><option key={t}>{t}</option>)}</select></label><div className="table-scroll" tabIndex={0} role="region" aria-label="Playoff bracket, scroll horizontally on small screens"><div className="playoff-tree" style={{height:tree.height+50}}><div className="playoff-headings">{rounds.map(r=><h2 key={r}>{r.replace(' Playoff','').replace('Conf.','Conference')}</h2>)}</div><svg className="bracket-lines" viewBox={`0 0 1120 ${tree.height}`} aria-hidden="true">{tree.nodes.flatMap(n=>n.children.map(c=>{const lit=c.game?winner(c.game)===selected:c.bye===selected;return <path key={`${n.game?.id}-${c.game?.id||c.bye}`} d={`M ${c.depth*280+240} ${c.y} H ${n.depth*280-20} V ${n.y} H ${n.depth*280}`} stroke={lit?branding(selected)?.color||'#c8f31d':'#38453b'} strokeWidth={lit?4:2} fill="none"/>}))}</svg>{tree.nodes.map(n=>n.game?<a className={`match-card tree-match ${[n.game.offense.toUpperCase(),n.game.defense.toUpperCase()].includes(selected)?'path-selected':''}`} style={{left:n.depth*280,top:n.y+50,'--path-color':branding(selected)?.color||'#c8f31d'} as React.CSSProperties} key={n.game.id} href={`/games/${n.game.id}`}><div>{n.game.date}<small>REPLAY ↗</small></div>{[[n.game.offense,n.game.offenseScore],[n.game.defense,n.game.defenseScore]].map(([team,score])=><strong key={String(team)}><span>{winner(n.game!)===String(team).toUpperCase()?'★ ':''}{String(team).toUpperCase()}</span><b>{score}</b></strong>)}</a>:<div className="bye-node" key={n.bye} style={{left:n.depth*280,top:n.y+50}}><b>{n.bye}</b><span>FIRST-ROUND BYE</span></div>)}</div></div><details><summary>View postseason results as a table</summary><div className="table-scroll"><table><thead><tr><th>Round</th><th>Matchup</th><th>Score</th><th>Winner</th></tr></thead><tbody>{postseason.map(g=><tr key={g.id}><td>{g.type}</td><td><a href={`/games/${g.id}`}>{g.offense.toUpperCase()} / {g.defense.toUpperCase()}</a></td><td>{g.offenseScore}–{g.defenseScore}</td><td>{winner(g)}</td></tr>)}</tbody></table></div></details></>}
